version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    platform: linux/amd64 # Fix for my M1 Chip Mac
    image: mysql:8.0.26 # upgrade from 5.7.22, which is broken
    restart: always
    environment:
      MYSQL_DATABASE: admin
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306